import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "b2bCampus",
  description: "Generated by create next app",
};

const KodchasanMedium = localFont({
  src: [{ path: "../../public/fonts/Kodchasan-Medium.ttf" }],

  variable: "--font-kodchasan-medium",
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${KodchasanMedium.variable}`}>
        {/* ${kodchasanNormal.variable} ${kodchasanLight.variable} */}
        {children}
      </body>
    </html>
  );
}
