import localFont from "next/font/local";
import "./globals.css";
import Header from "./Components/UiUx/Header";
import Footer from "./Components/UiUx/Footer";
import Image from "next/image";
import Whatsapp from "./Components/Page-Components/Whatsapp";
import Helpline from "./Components/Page-Components/Helpline";
import FooterNew from "./Components/UiUx/FooterNew";

export const metadata = {
  title: "b2bCampus",
  description: "Generated by create next app",
};

const KodchasanMedium = localFont({
  src: [{ path: "../../public/fonts/Kodchasan-Medium.ttf" }],

  variable: "--font-kodchasan-medium",
});


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${KodchasanMedium.variable}`}>
        <Header />
        {/* ${kodchasanNormal.variable} ${kodchasanLight.variable} */}
        {children}
        <div className="fixed bottom-4 left-4 z-50">
          <Whatsapp />
        </div>
        <div className="fixed bottom-4 right-4 z-50">
          <Helpline />
        </div>
        <FooterNew />
      </body>
    </html>
  );
}
